'use strict';function n(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var p=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function aa(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var q=aa(this);function r(a,b){if(b)a:{var c=q;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&p(c,a,{configurable:!0,writable:!0,value:b})}}
r("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,k){this.g=f;p(this,"description",{configurable:!0,writable:!0,value:k})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=q[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&p(d.prototype,a,{configurable:!0,writable:!0,value:function(){return t(n(this))}})}return a});function t(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function u(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:n(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function v(a){if(!(a instanceof Array)){a=u(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ba=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},w;
if(typeof Object.setPrototypeOf=="function")w=Object.setPrototypeOf;else{var y;a:{var ca={a:!0},z={};try{z.__proto__=ca;y=z.a;break a}catch(a){}y=!1}w=y?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var A=w;function B(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
r("WeakMap",function(a){function b(h){this.g=(g+=Math.random()+1).toString();if(h){h=u(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(h){var l=typeof h;return l==="object"&&h!==null||l==="function"}function e(h){if(!B(h,k)){var l=new c;p(h,k,{value:l})}}function f(h){var l=Object[h];l&&(Object[h]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),l=Object.seal({}),
m=new a([[h,2],[l,3]]);if(m.get(h)!=2||m.get(l)!=3)return!1;m.delete(h);m.set(l,4);return!m.has(h)&&m.get(l)==4}catch(x){return!1}}())return a;var k="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var g=0;b.prototype.set=function(h,l){if(!d(h))throw Error("Invalid WeakMap key");e(h);if(!B(h,k))throw Error("WeakMap key fail: "+h);h[k][this.g]=l;return this};b.prototype.get=function(h){return d(h)&&B(h,k)?h[k][this.g]:void 0};b.prototype.has=function(h){return d(h)&&B(h,
k)&&B(h[k],this.g)};b.prototype.delete=function(h){return d(h)&&B(h,k)&&B(h[k],this.g)?delete h[k][this.g]:!1};return b});
r("Map",function(a){function b(){var g={};return g.o=g.next=g.head=g}function c(g,h){var l=g[1];return t(function(){if(l){for(;l.head!=g[1];)l=l.o;for(;l.next!=l.head;)return l=l.next,{done:!1,value:h(l)};l=null}return{done:!0,value:void 0}})}function d(g,h){var l=h&&typeof h;l=="object"||l=="function"?f.has(h)?l=f.get(h):(l=""+ ++k,f.set(h,l)):l="p_"+h;var m=g[0][l];if(m&&B(g[0],l))for(g=0;g<m.length;g++){var x=m[g];if(h!==h&&x.key!==x.key||h===x.key)return{id:l,list:m,index:g,l:x}}return{id:l,list:m,
index:-1,l:void 0}}function e(g){this[0]={};this[1]=b();this.size=0;if(g){g=u(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var g=Object.seal({x:4}),h=new a(u([[g,"s"]]));if(h.get(g)!="s"||h.size!=1||h.get({x:4})||h.set({x:4},"t")!=h||h.size!=2)return!1;var l=h.entries(),m=l.next();if(m.done||m.value[0]!=g||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(x){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(g,h){g=g===0?0:g;var l=d(this,g);l.list||(l.list=this[0][l.id]=[]);l.l?l.l.value=h:(l.l={next:this[1],o:this[1].o,head:this[1],key:g,value:h},l.list.push(l.l),this[1].o.next=l.l,this[1].o=l.l,this.size++);return this};e.prototype.delete=function(g){g=d(this,g);return g.l&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.l.o.next=g.l.next,g.l.next.o=g.l.o,g.l.head=
null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].o=b();this.size=0};e.prototype.has=function(g){return!!d(this,g).l};e.prototype.get=function(g){return(g=d(this,g).l)&&g.value};e.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};e.prototype.keys=function(){return c(this,function(g){return g.key})};e.prototype.values=function(){return c(this,function(g){return g.value})};e.prototype.forEach=function(g,h){for(var l=this.entries(),m;!(m=l.next()).done;)m=
m.value,g.call(h,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var k=0;return e});
r("Set",function(a){function b(c){this.g=new Map;if(c){c=u(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var c=Object.seal({x:4}),d=new a(u([c]));if(!d.has(c)||d.size!=1||d.add(c)!=d||d.size!=1||d.add({x:4})!=d||d.size!=2)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||f.value[0].x!=4||
f.value[1]!=f.value[0]?!1:e.next().done}catch(k){return!1}}())return a;b.prototype.add=function(c){c=c===0?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(f){return c.call(d,f,f,e)})};return b});function C(a,b,c){if(a==null)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
r("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=C(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var k=0;k<f&&c<e;)if(d[c++]!=b[k++])return!1;return k>=f}});r("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});
r("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});r("String.prototype.includes",function(a){return a?a:function(b,c){return C(this,b,"includes").indexOf(b,c||0)!==-1}});
r("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(g){return g};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var k=0;!(f=b.next()).done;)e.push(c.call(d,f.value,k++))}else for(f=b.length,k=0;k<f;k++)e.push(c.call(d,b[k],k));return e}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var D=this||self;function da(a){var b=typeof a;b=b!="object"?b:a?Array.isArray(a)?"array":b:"null";return b=="array"||b=="object"&&typeof a.length=="number"}function E(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}function F(a,b){function c(){}c.prototype=b.prototype;a.F=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.I=function(d,e,f){for(var k=Array(arguments.length-2),g=2;g<arguments.length;g++)k[g-2]=arguments[g];return b.prototype[e].apply(d,k)}};function G(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,G);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}F(G,Error);G.prototype.name="CustomError";var ea=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};function fa(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function ha(a,b){for(var c in a)b.call(void 0,a[c],c,a)};function H(a,b){this.i=a;this.j=b;this.h=0;this.g=null}H.prototype.get=function(){if(this.h>0){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.i();return a};function I(a,b){a.j(b);a.h<100&&(a.h++,b.next=a.g,a.g=b)};var J;function ia(){if(typeof MessageChannel!=="undefined"){var a=new MessageChannel,b={},c=b;a.port1.onmessage=function(){if(b.next!==void 0){b=b.next;var d=b.v;b.v=null;d()}};return function(d){c.next={v:d};c=c.next;a.port2.postMessage(0)}}return function(d){D.setTimeout(d,0)}};function ja(a){D.setTimeout(function(){throw a;},0)};function ka(){this.h=this.g=null}ka.prototype.add=function(a,b){var c=la.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c};function ma(){var a=na,b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b}var la=new H(function(){return new K},function(a){return a.reset()});function K(){this.next=this.g=this.h=null}K.prototype.set=function(a,b){this.h=a;this.g=b;this.next=null};K.prototype.reset=function(){this.next=this.g=this.h=null};var L,M=!1,na=new ka;function N(a,b){L||oa();M||(L(),M=!0);na.add(a,b)}function oa(){if(D.Promise&&D.Promise.resolve){var a=D.Promise.resolve(void 0);L=function(){a.then(pa)}}else L=function(){var b=pa;J||(J=ia());J(b)}}function pa(){for(var a;a=ma();){try{a.h.call(a.g)}catch(b){ja(b)}I(la,a)}M=!1};function O(){};function P(a){this.g=0;this.u=void 0;this.j=this.h=this.i=null;this.m=this.s=!1;if(a!=O)try{var b=this;a.call(void 0,function(c){Q(b,2,c)},function(c){Q(b,3,c)})}catch(c){Q(this,3,c)}}function qa(){this.next=this.i=this.h=this.j=this.g=null;this.m=!1}qa.prototype.reset=function(){this.i=this.h=this.j=this.g=null;this.m=!1};var ra=new H(function(){return new qa},function(a){a.reset()});function sa(a,b,c){var d=ra.get();d.j=a;d.h=b;d.i=c;return d}function ta(){new P(function(){})}
P.prototype.then=function(a,b,c){return ua(this,typeof a==="function"?a:null,typeof b==="function"?b:null,c)};P.prototype.$goog_Thenable=!0;P.prototype.cancel=function(a){if(this.g==0){var b=new R(a);N(function(){va(this,b)},this)}};function va(a,b){if(a.g==0)if(a.i){var c=a.i;if(c.h){for(var d=0,e=null,f=null,k=c.h;k&&(k.m||(d++,k.g==a&&(e=k),!(e&&d>1)));k=k.next)e||(f=k);e&&(c.g==0&&d==1?va(c,b):(f?(d=f,d.next==c.j&&(c.j=d),d.next=d.next.next):wa(c),xa(c,e,3,b)))}a.i=null}else Q(a,3,b)}
function ya(a,b){a.h||a.g!=2&&a.g!=3||za(a);a.j?a.j.next=b:a.h=b;a.j=b}function ua(a,b,c,d){var e=sa(null,null,null);e.g=new P(function(f,k){e.j=b?function(g){try{var h=b.call(d,g);f(h)}catch(l){k(l)}}:f;e.h=c?function(g){try{var h=c.call(d,g);h===void 0&&g instanceof R?k(g):f(h)}catch(l){k(l)}}:k});e.g.i=a;ya(a,e);return e.g}P.prototype.G=function(a){this.g=0;Q(this,2,a)};P.prototype.H=function(a){this.g=0;Q(this,3,a)};
function Q(a,b,c){if(a.g==0){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.g=1;a:{var d=c,e=a.G,f=a.H;if(d instanceof P){ya(d,sa(e||O,f||null,a));var k=!0}else{if(d)try{var g=!!d.$goog_Thenable}catch(l){g=!1}else g=!1;if(g)d.then(e,f,a),k=!0;else{if(E(d))try{var h=d.then;if(typeof h==="function"){Aa(d,h,e,f,a);k=!0;break a}}catch(l){f.call(a,l);k=!0;break a}k=!1}}}k||(a.u=c,a.g=b,a.i=null,za(a),b!=3||c instanceof R||Ba(a,c))}}
function Aa(a,b,c,d,e){function f(h){g||(g=!0,d.call(e,h))}function k(h){g||(g=!0,c.call(e,h))}var g=!1;try{b.call(a,k,f)}catch(h){f(h)}}function za(a){a.s||(a.s=!0,N(a.D,a))}function wa(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.j=null);return b}P.prototype.D=function(){for(var a;a=wa(this);)xa(this,a,this.g,this.u);this.s=!1};
function xa(a,b,c,d){if(c==3&&b.h&&!b.m)for(;a&&a.m;a=a.i)a.m=!1;if(b.g)b.g.i=null,Ca(b,c,d);else try{b.m?b.j.call(b.i):Ca(b,c,d)}catch(e){Da.call(null,e)}I(ra,b)}function Ca(a,b,c){b==2?a.j.call(a.i,c):a.h&&a.h.call(a.i,c)}function Ba(a,b){a.m=!0;N(function(){a.m&&Da.call(null,b)})}var Da=ja;function R(a){G.call(this,a)}F(R,G);R.prototype.name="cancel";function S(a,b,c,d,e){e=e===void 0?{}:e;d=e.B===void 0?void 0:e.B;e=e.A===void 0?!1:e.A;this.u=a;this.i=b;this.m=0;this.s=!!c;this.h=d||null;this.j=e;this.g=[];ta()}function T(){}S.prototype=ba(T.prototype);S.prototype.constructor=S;if(A)A(S,T);else for(var U in T)if(U!="prototype")if(Object.defineProperties){var Ea=Object.getOwnPropertyDescriptor(T,U);Ea&&Object.defineProperty(S,U,Ea)}else S[U]=T[U];S.F=T.prototype;
S.prototype.sendMessage=function(a){a=a.message;this.h&&this.j&&(a.messagingToken=this.h);var b=a.data;if(typeof b!="undefined"&&b!=null){var c=[],d;for(d in b)if(typeof b[d]!=="function"){var e=d+" = ";try{e+=b[d]}catch(f){e+="*** "+f+" ***"}c.push(e)}}this.u.postMessage(a,this.i==="null"?"*":this.i)};
function V(a,b,c){if(a.s){var d=a.m++,e={type:"q"};e.data=c;e.app="__AMPHTML__";e.requestid=d;e.name=b;try{a.sendMessage({message:e,channel:a})}catch(f){throw f;}}else{a:{for(d=0;d<a.g.length;d++)if(e=a.g[d],e.name==b){e.C=c;break a}a.g.push({name:b,C:c,J:[]})}a=new P(O);Q(a,2)}};var W=new Set;function Fa(a,b){var c=W.size;a===0&&c!==0?(a={},V(b,"dirtyForm",(a.hasDirtyForm=!0,a))):a!==0&&c===0&&(a={},V(b,"dirtyForm",(a.hasDirtyForm=!1,a)))};function Ga(a,b){ha(b,function(c,d){d=="style"?a.style.cssText=c:d=="class"?a.className=c:d=="for"?a.htmlFor=c:Ha.hasOwnProperty(d)?a.setAttribute(Ha[d],c):d.lastIndexOf("aria-",0)==0||d.lastIndexOf("data-",0)==0?a.setAttribute(d,c):a[d]=c})}var Ha={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Ia(a,b,c){var d=arguments,e=document,f=d[1];var k=String(d[0]);k=String(k);e.contentType==="application/xhtml+xml"&&(k=k.toLowerCase());k=e.createElement(k);f&&(typeof f==="string"?k.className=f:Array.isArray(f)?k.className=f.join(" "):Ga(k,f));d.length>2&&Ja(e,k,d,2);return k}
function Ja(a,b,c,d){function e(g){g&&b.appendChild(typeof g==="string"?a.createTextNode(g):g)}for(;d<c.length;d++){var f=c[d];if(!da(f)||E(f)&&f.nodeType>0)e(f);else{a:{if(f&&typeof f.length=="number"){if(E(f)){var k=typeof f.item=="function"||typeof f.item=="string";break a}if(typeof f==="function"){k=typeof f.item=="function";break a}}k=!1}ea(k?fa(f):f,e)}}}function Ka(a,b){Ja(a.nodeType==9?a:a.ownerDocument||a.document,a,arguments,1)};var La=["http:","https:"];var X={},Ma=(X["AMP-LIGHTBOX"]=4,X["AMP-IMAGE-LIGHTBOX"]=3,X["AMP-SIDEBAR"]=6,X);
function Na(a){if(a.attributeName!=="class")return!1;var b=a.target,c=new Set(a.oldValue?a.oldValue.split(" ").filter(function(e){return e}):[]),d=new Set(Array.from(b.classList));a=[].concat(v(d)).filter(function(e){return!c.has(e)});b=[].concat(v(c)).filter(function(e){return!d.has(e)});a=u([].concat(v(a),v(b)));for(b=a.next();!b.done;b=a.next())if(b=b.value,!b.startsWith("i-amphtml-")&&!b.startsWith("amp-"))return!1;return!0}
function Oa(a,b){return a.hasAttribute("["+b+"]")||a.hasAttribute("data-amp-bind-"+b)};var Y=null;
window.addEventListener("click",function(a){if(!a.defaultPrevented&&a.target instanceof Element){var b=a.target;Z();if(Y){var c=Y;if(b.classList.contains("amp-carousel-button")){var d=b.closest("AMP-CAROUSEL");d&&(!d.hasAttribute("type")||d.hasAttribute("type")&&d.getAttribute("type").toLowerCase()==="carousel")&&(d={},V(c,"userInteraction",(d.ampComponentType=2,d)))}d=Y;if((c=b.closest("A".toString()))&&La.includes(c.protocol)){V(d,"anchorClickThrough",null);a:switch(d=D.AMP.viewer.getParam("platform"),b=
c.href,c=c.dataset.saferedirecturl,parseInt(d,10)){case 0:d=new URL("gmail-link://");d.searchParams.set("msgId","m");d.searchParams.set("url",b);d.searchParams.set("safeRedirectUrl",c);b=d.toString();break a;case 1:d=new URL("safelink://");d.searchParams.set("url",b);d.searchParams.set("safe_redirect_url",c);b=d.toString();break a;default:b=c||b}c=Ia("A",{target:"_blank",rel:"noopener noreferrer",style:"display: none"});d=new MouseEvent("click",{cancelable:!0});c.setAttribute("href",b);Ka(document.body,
c);c.dispatchEvent(d);c&&c.parentNode&&c.parentNode.removeChild(c);a.preventDefault()}}}});document.addEventListener("amp:form-dirtiness-change",function(a){Z();if(Y){var b=Y,c=W.size,d=a.target;a.detail.isDirty?W.add(d):W.delete(d);Fa(c,b)}});document.addEventListener("slideChange",function(a){Z();if(Y){var b=Y,c=a.target.getAttribute("type").toLowerCase()==="slides",d=a.type==="slideChange";a=a.data.actionTrust===3;c&&d&&a&&(c={},V(b,"userInteraction",(c.ampComponentType=2,c)))}});
document.addEventListener("change",function(a){if(a instanceof CustomEvent&&(Z(),Y)){var b=Y;a=a.target;var c=a.tagName==="TEXTAREA".toString()||a.tagName==="INPUT".toString();a.closest("AMP-AUTOCOMPLETE")&&c&&(a={},V(b,"userInteraction",(a.ampComponentType=9,a)))}});
(new MutationObserver(function(a){a=u(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,Z(),Y){var c=Y;switch(b.type){case "attributes":if(b.attributeName&&b.oldValue===b.target.getAttribute(b.attributeName))break;if(b.attributeName==="expanded"){var d=b.target;d.tagName==="SECTION".toString()&&d.parentElement&&d.parentElement.tagName==="AMP-ACCORDION"&&(d={},V(c,"userInteraction",(d.ampComponentType=1,d)))}if(b.attributeName==="hidden"&&b.oldValue===""&&(d=Ma[b.target.tagName])){var e={};V(c,
"userInteraction",(e.ampComponentType=d,e))}b.attributeName==="selected"&&(d=b.target,e=d.closest("AMP-SELECTOR"),d.hasAttribute("option")&&e&&(e.hasAttribute("multiple")||b.oldValue===null)&&(d={},V(c,"userInteraction",(d.ampComponentType=5,d))));var f,k=b;d=c;if(k.attributeName==="class"){e=k.target;if(f=e.tagName==="FORM".toString())f=k.oldValue,e=e.classList,f=!(f?f.split(" "):[]).includes("amp-form-submitting")&&e.contains("amp-form-submitting");f&&(e={},V(d,"userInteraction",(e.ampComponentType=
8,e)))}d=b;d.attributeName&&!Na(d)&&Oa(d.target,d.attributeName)&&(d={},V(c,"userInteraction",(d.ampComponentType=7,d)));break;case "childList":b.addedNodes.length===1&&b.removedNodes.length===1&&(d=b.addedNodes[0],e=b.removedNodes[0],d.nodeType===Node.TEXT_NODE&&e.nodeType===Node.TEXT_NODE&&d.textContent!==e.textContent&&Oa(d.parentElement,"text")&&(d={},V(c,"userInteraction",(d.ampComponentType=7,d))))}c=Y;if(b.removedNodes.length!==0){d=W.size;b=u(b.removedNodes);for(e=b.next();!e.done;e=b.next())if(e=
e.value,e.nodeType===Node.ELEMENT_NODE)for(e=u(e.tagName==="FORM".toString()?[e]:e.querySelectorAll("FORM".toString())),f=e.next();!f.done;f=e.next())W.delete(f.value);Fa(d,c)}}})).observe(document.getRootNode(),{attributeOldValue:!0,attributes:!0,childList:!0,subtree:!0});function Z(){if(!Y&&window.AMP&&window.AMP.viewer){var a=window.AMP.viewer.getParam("messagingToken");Y=new S(window.parent,window.AMP.viewer.getParam("origin"),!0,!1,{B:a||void 0,A:!0})}};
